package store

var migrations = []string{
	`CREATE TABLE IF NOT EXISTS users (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		username TEXT UNIQUE NOT NULL,
		email TEXT UNIQUE NOT NULL,
		password_hash TEXT NOT NULL,
		role TEXT NOT NULL DEFAULT 'viewer',
		avatar_url TEXT,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
		last_login DATETIME
	)`,
	`CREATE TABLE IF NOT EXISTS ssh_keys (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		user_id INTEGER NOT NULL REFERENCES users(id),
		name TEXT NOT NULL,
		public_key TEXT NOT NULL,
		fingerprint TEXT NOT NULL,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS projects (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT UNIQUE NOT NULL,
		description TEXT,
		repo_url TEXT NOT NULL,
		repo_type TEXT NOT NULL,
		default_branch TEXT DEFAULT 'main',
		config TEXT NOT NULL,
		created_by INTEGER REFERENCES users(id),
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS builds (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		project_id INTEGER NOT NULL REFERENCES projects(id),
		number INTEGER NOT NULL,
		status TEXT NOT NULL DEFAULT 'pending',
		trigger TEXT NOT NULL,
		branch TEXT,
		commit_sha TEXT,
		parameters TEXT,
		log TEXT,
		started_at DATETIME,
		finished_at DATETIME,
		duration_ms INTEGER,
		UNIQUE(project_id, number)
	)`,
	`CREATE TABLE IF NOT EXISTS artifacts (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		build_id INTEGER NOT NULL REFERENCES builds(id),
		name TEXT NOT NULL,
		path TEXT NOT NULL,
		size INTEGER,
		sha256 TEXT DEFAULT '',
		content_type TEXT DEFAULT '',
		downloads INTEGER DEFAULT 0,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS workers (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL,
		address TEXT NOT NULL,
		token_hash TEXT NOT NULL,
		labels TEXT,
		pool TEXT DEFAULT '',
		max_concurrent_builds INTEGER DEFAULT 4,
		status TEXT DEFAULT 'offline',
		last_heartbeat DATETIME,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS plugins (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT UNIQUE NOT NULL,
		version TEXT NOT NULL,
		description TEXT,
		enabled BOOLEAN DEFAULT TRUE,
		config TEXT,
		installed_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS env_vars (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		scope TEXT NOT NULL,
		project_id INTEGER,
		name TEXT NOT NULL,
		value TEXT NOT NULL,
		is_secret BOOLEAN DEFAULT FALSE,
		description TEXT,
		UNIQUE(scope, project_id, name)
	)`,
	`CREATE TABLE IF NOT EXISTS credentials (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT UNIQUE NOT NULL,
		type TEXT NOT NULL,
		host TEXT NOT NULL DEFAULT '',
		username TEXT,
		password TEXT,
		private_key TEXT,
		public_key TEXT,
		token TEXT,
		description TEXT,
		is_secret BOOLEAN DEFAULT TRUE,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS idx_credentials_type ON credentials(type)`,
	`CREATE INDEX IF NOT EXISTS idx_credentials_host ON credentials(host)`,
	`CREATE TABLE IF NOT EXISTS vcs_roots (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT UNIQUE NOT NULL,
		type TEXT NOT NULL,
		url TEXT NOT NULL,
		branch TEXT DEFAULT 'main',
		credential_id INTEGER REFERENCES credentials(id),
		poll_interval INTEGER DEFAULT 60,
		auto_checkout BOOLEAN DEFAULT TRUE,
		config TEXT DEFAULT '{}',
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS build_templates (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT UNIQUE NOT NULL,
		config TEXT NOT NULL,
		description TEXT,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`,
	`ALTER TABLE projects ADD COLUMN vcs_root_id INTEGER REFERENCES vcs_roots(id)`,
	`ALTER TABLE projects ADD COLUMN template_id INTEGER REFERENCES build_templates(id)`,
	`ALTER TABLE builds ADD COLUMN wait_dependency_on INTEGER REFERENCES builds(id)`,
	`ALTER TABLE builds ADD COLUMN retried_from INTEGER REFERENCES builds(id)`,
	`ALTER TABLE builds ADD COLUMN pinned BOOLEAN DEFAULT FALSE`,
	`ALTER TABLE workers ADD COLUMN pool TEXT DEFAULT ''`,
	`ALTER TABLE artifacts ADD COLUMN sha256 TEXT DEFAULT ''`,
	`ALTER TABLE artifacts ADD COLUMN content_type TEXT DEFAULT ''`,
	`ALTER TABLE artifacts ADD COLUMN downloads INTEGER DEFAULT 0`,
	`CREATE TABLE IF NOT EXISTS notification_channels (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT UNIQUE NOT NULL,
		type TEXT NOT NULL,
		config TEXT NOT NULL DEFAULT '{}',
		enabled BOOLEAN DEFAULT TRUE,
		conditions TEXT DEFAULT '{}',
		description TEXT,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS notification_events (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		channel_id INTEGER NOT NULL REFERENCES notification_channels(id),
		build_id INTEGER REFERENCES builds(id),
		event_type TEXT NOT NULL,
		payload TEXT NOT NULL,
		status TEXT NOT NULL DEFAULT 'pending',
		error_message TEXT,
		delivered_at DATETIME,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS idx_notification_events_channel ON notification_events(channel_id)`,
	`CREATE INDEX IF NOT EXISTS idx_notification_events_build ON notification_events(build_id)`,
	`CREATE TABLE IF NOT EXISTS build_stats (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		project_id INTEGER NOT NULL REFERENCES projects(id),
		date TEXT NOT NULL,
		total_builds INTEGER DEFAULT 0,
		success_count INTEGER DEFAULT 0,
		failed_count INTEGER DEFAULT 0,
		avg_duration_ms INTEGER DEFAULT 0,
		UNIQUE(project_id, date)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_build_stats_project ON build_stats(project_id)`,
	`CREATE TABLE IF NOT EXISTS audit_logs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		user_id INTEGER,
		username TEXT,
		action TEXT NOT NULL,
		resource_type TEXT,
		resource_id TEXT,
		detail TEXT,
		ip TEXT,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON audit_logs(user_id)`,
	`CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at)`,
	`CREATE TABLE IF NOT EXISTS api_tokens (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		user_id INTEGER NOT NULL REFERENCES users(id),
		name TEXT NOT NULL,
		token_hash TEXT UNIQUE NOT NULL,
		token_prefix TEXT NOT NULL,
		scopes TEXT DEFAULT '[]',
		expires_at DATETIME,
		last_used_at DATETIME,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS idx_api_tokens_user ON api_tokens(user_id)`,
	`CREATE INDEX IF NOT EXISTS idx_api_tokens_hash ON api_tokens(token_hash)`,
	`CREATE TABLE IF NOT EXISTS build_approvals (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		build_id INTEGER NOT NULL REFERENCES builds(id),
		user_id INTEGER NOT NULL REFERENCES users(id),
		username TEXT,
		status TEXT NOT NULL DEFAULT 'pending',
		comment TEXT,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
		resolved_at DATETIME
	)`,
	`CREATE INDEX IF NOT EXISTS idx_build_approvals_build ON build_approvals(build_id)`,
	`CREATE INDEX IF NOT EXISTS idx_build_approvals_status ON build_approvals(status)`,
	`CREATE TABLE IF NOT EXISTS test_results (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		build_id INTEGER NOT NULL REFERENCES builds(id),
		total INTEGER DEFAULT 0,
		passed INTEGER DEFAULT 0,
		failed INTEGER DEFAULT 0,
		skipped INTEGER DEFAULT 0,
		duration_ms INTEGER DEFAULT 0,
		report_xml TEXT,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS idx_test_results_build ON test_results(build_id)`,
	`CREATE TABLE IF NOT EXISTS deployment_envs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		project_id INTEGER NOT NULL REFERENCES projects(id),
		name TEXT NOT NULL,
		description TEXT,
		config TEXT DEFAULT '{}',
		last_build_id INTEGER,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS idx_deployment_envs_project ON deployment_envs(project_id)`,
	`CREATE TABLE IF NOT EXISTS project_groups (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT UNIQUE NOT NULL,
		description TEXT,
		parent_id INTEGER REFERENCES project_groups(id),
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS build_queue_items (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		build_id INTEGER NOT NULL REFERENCES builds(id),
		project_id INTEGER NOT NULL,
		project_name TEXT,
		priority INTEGER DEFAULT 0,
		status TEXT NOT NULL DEFAULT 'queued',
		trigger TEXT,
		branch TEXT,
		queued_at DATETIME DEFAULT CURRENT_TIMESTAMP,
		started_at DATETIME
	)`,
	`CREATE INDEX IF NOT EXISTS idx_build_queue_status ON build_queue_items(status, priority DESC, queued_at)`,
	`ALTER TABLE builds ADD COLUMN approval_required BOOLEAN DEFAULT FALSE`,
	`ALTER TABLE builds ADD COLUMN approved_by INTEGER`,
	`ALTER TABLE builds ADD COLUMN approved_at DATETIME`,
	`ALTER TABLE builds ADD COLUMN timeout_sec INTEGER DEFAULT 0`,
	`ALTER TABLE builds ADD COLUMN test_result_id INTEGER`,
	`ALTER TABLE projects ADD COLUMN group_id INTEGER REFERENCES project_groups(id)`,
	`CREATE TABLE IF NOT EXISTS git_hooks (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		project_id INTEGER NOT NULL REFERENCES projects(id),
		name TEXT NOT NULL,
		event TEXT NOT NULL,
		branch TEXT DEFAULT '',
		secret TEXT DEFAULT '',
		enabled BOOLEAN DEFAULT TRUE,
		build_params TEXT DEFAULT '{}',
		description TEXT,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE INDEX IF NOT EXISTS idx_git_hooks_project ON git_hooks(project_id)`,
	`ALTER TABLE plugins ADD COLUMN author TEXT DEFAULT ''`,
	`ALTER TABLE plugins ADD COLUMN path TEXT DEFAULT ''`,
	`ALTER TABLE plugins ADD COLUMN source TEXT DEFAULT 'builtin'`,
	`ALTER TABLE plugins ADD COLUMN steps TEXT DEFAULT '[]'`,
	`ALTER TABLE plugins ADD COLUMN triggers TEXT DEFAULT '[]'`,
	`ALTER TABLE plugins ADD COLUMN ui_extensions TEXT DEFAULT '[]'`,
	`ALTER TABLE plugins ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP`,
}